### ISSUE TITLE
Display Movie Directors method

### ISSUE THREAD

**Issue by gilroy** [Johnny00520/Jin_Cheng_CSCI2270_FinalProject#1]
From the main menu, options (4) and (5) have the same output. Because option (4) reads "Display movie directors", this is slightly confusing because there is not movie director output. The printMovieDirectors method likely do exactly that- print the movie director for every given movie.

**Comment by Johnny00520** [comment]
I'm sorry I don't understand. The option (4) is to print what we read from the file. And the option (5) of advanced search is just key word. For example, you can try to type 'The'
